name: mobile_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  avnu_provider: ^0.1.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.2
  google_fonts: ^6.3.0
  http: ^1.5.0
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  starknet: ^0.2.0
  starknet_provider: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

